# Generated by Django 3.2.7 on 2022-07-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20220725_0049'),
        ('algorithm', '0003_delete_algorithmparameters'),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('channel', 'algorithm', 'date_time')},
        ),
    ]
