# Generated by Django 3.2.13 on 2022-11-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('algorithm', '0001_initial'),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('channel', 'algorithm', 'img')},
        ),
    ]
