# Generated by Django 3.2.13 on 2022-11-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_alert_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='num_objects',
            field=models.IntegerField(default=1, verbose_name='目标数量'),
        ),
    ]
