# Generated by Django 3.2.13 on 2022-08-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_alert_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='img_unmark',
            field=models.CharField(max_length=256, null=True, verbose_name='报警图片'),
        ),
    ]
