# Generated by Django 3.2.13 on 2022-08-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_img_unmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_misreported',
            field=models.BooleanField(default=False, verbose_name='误报'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='img_unmark',
            field=models.CharField(max_length=256, null=True, verbose_name='未标注图片'),
        ),
    ]
