# Here is the command code
IMG_CMD_GET_LATEST_IMAGE = 100
IMG_CMD_CHANNEL_UPDATED = 101
IMG_CMD_OBJECT_DETECTED = 102
IMG_CMD_CHANNEL_ALG_CHANGED = 103
IMG_CMD_CHANNEL_CONFIGURED = 104
IMG_CMD_CHANNEL_GET_ONLINE = 105
IMG_CMD_CHANNEL_DELETED = 106
IMG_CMD_DB_KEEP_ALIVE = 107

# Here is the response code
IMG_CODE_SUCCESS = 0
IMG_CODE_INVALID_CMD = 1000
IMG_CODE_CHANNEL_NOT_FOUND = 1001

