# Generated by Django 3.2.13 on 2022-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='图片/图标名称')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名称, 可以在/static/images获取')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('auth_code', models.CharField(max_length=32, unique=True, verbose_name='授权码')),
                ('verification_code', models.CharField(max_length=32, null=True, verbose_name='激活码')),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=64, verbose_name='平台名称')),
                ('copyright', models.CharField(max_length=512, verbose_name='版权信息')),
            ],
        ),
    ]
