# Generated by Django 3.2.13 on 2022-08-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='verification_code',
            field=models.CharField(max_length=32, null=True, verbose_name='激活码'),
        ),
    ]
