# Generated by Django 3.2.13 on 2022-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_name_projectinfo_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='图片/图标名称')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名称, 可以在/static/images获取')),
            ],
        ),
    ]
