# Generated by Django 3.2.13 on 2022-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_imageicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=64, verbose_name='平台名称')),
                ('copyright', models.CharField(max_length=512, verbose_name='版权信息')),
            ],
        ),
    ]
