# Generated by Django 3.2.13 on 2022-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='英文名称')),
                ('name_ch', models.CharField(max_length=32, verbose_name='中文名称')),
                ('event_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmDefaultParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyze_interval', models.IntegerField(default=1000, verbose_name='分析问题(ms)')),
                ('alert_interval', models.IntegerField(default=30, verbose_name='报警间隔')),
                ('alert_threshold', models.FloatField(default=0.5, verbose_name='报警阈值')),
                ('alert_times', models.CharField(max_length=1792, null=True, verbose_name='报警时段')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
