# Generated by Django 3.2.7 on 2022-07-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20220723_0142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgorithmParameters',
        ),
    ]
