# Generated by Django 3.2.13 on 2022-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_delete_algorithmparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmDefaultParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyze_interval', models.IntegerField(default=1000, verbose_name='分析问题(ms)')),
                ('alert_interval', models.IntegerField(default=30, verbose_name='报警间隔')),
                ('alert_threshold', models.FloatField(default=0.5, verbose_name='报警阈值')),
                ('alert_times', models.CharField(max_length=1792, null=True, verbose_name='报警时段')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
