# Generated by Django 3.2.13 on 2022-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_algorithmdefaultparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='英文名称'),
        ),
    ]
