# Generated by Django 3.2.13 on 2022-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_alter_algorithm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='event_type',
            field=models.IntegerField(null=True),
        ),
    ]
