version: "1.0.0"

services:
  mysqlsurv:
    image:
      mysql:8.0
    ports:
      - "3307:3306"
    volumes: 
      - survmanage-mysql-data:/var/lib/mysql
    networks:
      survmanagenetwork:
        aliases:
          - mysqlsurv
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=survmanage

  survmanage:
    image:
      survmanage:latest
    ports:
      - "6789:6789"
    volumes:
      - /docker:/docker
      - /bin:/hostinfo/bin
      - /usr/bin:/hostinfo/usr/bin
      - /usr/lib:/hostinfo/usr/lib
      - /proc:/hostinfo/proc
      - /etc/netplan:/etc/netplan
      - survmanage-dynamic_data:/dynamic_data
    networks:
      survmanagenetwork:
        aliases:
          - survmanage
      survauthnetwork:
        aliases:
          - survmanage
    depends_on:
      - mysqlsurv
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=survmanage
      - MYSQL_HOST=mysqlsurv
      - MYSQL_PORT=3306
      - SURVMANAGE_PORT=6789
      - AUTHSERVER_HOST=ai.hiibms.com  # survauthserver
      - AUTHSERVER_PORT=9998  # 9090  # Should use port 9998 exposed by nginx if run on different host
      - IMAGESERVER_HOST=imageserver
      - IMAGESERVER_PORT=6790
      - DYNAMIC_DATA_PATH=/dynamic_data
      - UPGRADE_FLAG_FILE=/docker/upgrade_flag
      - RESET_FLAG_FILE=/docker/reset_flag
      - HOSTINFO_ROOT=/hostinfo

  imageserver:
    image:
      imageserver:latest
    runtime:
      nvidia
    # ports:
    #  - "6790:6790"
    volumes:
      - /etc/netplan:/etc/netplan
      - survmanage-dynamic_data:/dynamic_data
    networks:
      survmanagenetwork:
        aliases:
          - imageserver
    depends_on:
      - mysqlsurv
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=survmanage
      - MYSQL_HOST=mysqlsurv
      - MYSQL_PORT=3306
      - IMAGESERVER_HOST=imageserver
      - IMAGESERVER_PORT=6790
      - MODEL_PATH=/checkpoints/best-20221015.pt
      - MODEL_DEVICE=cuda:1
      - DYNAMIC_DATA_PATH=/dynamic_data
      - MAX_CAMERA=8

  survmanagenginx:
    image:
      survmanagenginx:latest
    ports:
      - "9999:9999"
    networks:
      - survmanagenetwork
    depends_on:
      - survmanage

networks:
  survmanagenetwork: {}
  survauthnetwork: {}

volumes:
  survmanage-mysql-data: {}
  survmanage-dynamic_data: {}
