version: "1.0.0"

services:
  mysqlsurv:
    image:
      mysql:8.0
    ports:
      - "3307:3306"
    volumes: 
      - survmanage-mysql-data:/var/lib/mysql
    networks:
      survnetwork:
        aliases:
          - mysqlsurv
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=survmanage

  survmanage:
    image:
      survmanage:latest
    ports:
      - "6789:6789"
    volumes:
      - survmanage-dynamic_data:/dynamic_data
    networks:
      survnetwork:
        aliases:
          - survmanage
    depends_on:
      - mysqlsurv
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=survmanage
      - MYSQL_HOST=mysqlsurv
      - MYSQL_PORT=3306
      - SURVMANAGE_PORT=6789
      - AUTHSERVER_HOST=survauthserver
      - AUTHSERVER_PORT=9998
      - IMAGESERVER_HOST=imageserver
      - IMAGESERVER_PORT=6790
      - DYNAMIC_DATA_PATH=/dynamic_data

  imageserver:
    image:
      imageserver:latest
    runtime:
      nvidia
    ports:
      - "6790:6790"
    volumes:
      - survmanage-dynamic_data:/dynamic_data
    networks:
      survnetwork:
        aliases:
          - imageserver
    depends_on:
      - mysqlsurv
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=survmanage
      - MYSQL_HOST=mysqlsurv
      - MYSQL_PORT=3306
      - IMAGESERVER_HOST=imageserver
      - IMAGESERVER_PORT=6790
      - MODEL_PATH=/checkpoints/yolov5s.pt
      - MODEL_DEVICE=cuda:1
      - DYNAMIC_DATA_PATH=/dynamic_data
      - MAX_CAMERA=8

  survmanagenginx:
    image:
      survmanagenginx:latest
    ports:
      - "9999:81"
    networks:
      - survnetwork
    depends_on:
      - survmanage

networks:
  survnetwork: {}

volumes:
  survmanage-mysql-data: {}
  survmanage-dynamic_data: {}
