version: "1.0.0"

services:
  msyqlsurv:
    image:
      mysql:8.0
    ports:
      - "3307:3306"
    volumes: 
      - survmanage-mysql-data:/var/lib/mysql
    networks:
      survmanagenetwork:
        aliases:
          - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=survmanage

#  survmanage:
#    image:
#      survmanage:latest
#    ports:
#      - "6789:6789"
#    networks:
#      survmanagenetwork:
#        aliases:
#          - survmanage
#      survauthnetwork:
#        aliases:
#          - survmanage
#    depends_on:
#      - msyqlsurv
#    environment:
#      - MYSQL_USERNAME=root
#      - MYSQL_PASSWORD=12345678
#      - MYSQL_DATABASE=survmanage
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=3307
#      - AUTHSERVER_HOST=survauthserver
#      - AUTHSERVER_PORT=9998
#      - IMAGESERVER_HOST=imageserver
#      - IMAGESERVER_PORT=6790
#      - DYNAMIC_DATA_PATH=/dynamic_data

#  imageserver:
#    image:
#      imageserver:latest
#    ports:
#      - "6790:6790"
#    networks:
#      survmanagenetwork:
#        aliases:
#          - imageserver
#    depends_on:
#      - msyqlsurv
#    environment:
#      - MYSQL_USERNAME=root
#      - MYSQL_PASSWORD=12345678
#      - MYSQL_DATABASE=survmanage
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=3307
#      - MODEL_PATH="/checkpoints/yolov5s.pt"
#      - MODEL_DEVICE="cuda:1"
#      - DYNAMIC_DATA_PATH=/dynamic_data

#  survmanagenginx:
#    image:
#      survmanagenginx:latest
#    ports:
#      - "9999:80"
#    networks:
#      - survmanagenetwork
#    depends_on:
#      - survmanage

networks:
  survauthnetwork: {}
  survmanagenetwork: {}

volumes:
  survmanage-mysql-data: {}
  survmanage-dynamic_data: {}
