FROM node:latest
# reference :https://blog.csdn.net/qq_35593448/article/details/124155905 (3. ffmpeg+jsmpeg+node)
RUN apt-get update
RUN apt-get install ffmpeg -y
RUN cd /
RUN git clone https://gitee.com/luopub/jsmpeg
# RUN cd /jsmpeg && pwd
# RUN cd /jsmpeg && npm install
RUN cd /jsmpeg && npm install ws
RUN cd /jsmpeg && npm install http-server -g
COPY docker-entrypoint-node-ffmpeg.sh /
RUN chmod +x /docker-entrypoint-node-ffmpeg.sh
CMD /docker-entrypoint-node-ffmpeg.sh
