# Generated by Django 3.2.13 on 2022-09-17 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenzhiMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BenzhiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenzhiReportUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenzhiSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32, unique=True)),
                ('event_type_name', models.CharField(max_length=32, unique=True)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('subscribe_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribe_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenzhiEventToAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('algorithm', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('event_type', 'algorithm')},
            },
        ),
    ]
