# Generated by Django 3.2.13 on 2022-11-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenzhiReportUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL to Report Alert')),
                ('platform_name', models.CharField(default='本质', max_length=32, verbose_name='Report Platform Name')),
                ('provider_name', models.CharField(default='美云数字', max_length=32, verbose_name='ProviderName')),
                ('enabled', models.BooleanField(default=True, verbose_name='Report Enabled')),
                ('metadata', models.CharField(max_length=2048, null=True, verbose_name='Metadata (key, value) pairs in JSON format')),
            ],
        ),
        migrations.CreateModel(
            name='BenzhiSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=True)),
                ('algorithm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='algorithm.algorithm')),
            ],
        ),
    ]
