# Generated by Django 3.2.13 on 2022-09-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benzhisubscription',
            name='subscribe_time',
        ),
        migrations.RemoveField(
            model_name='benzhisubscription',
            name='unsubscribe_time',
        ),
        migrations.AlterField(
            model_name='benzhisubscription',
            name='event_type_name',
            field=models.CharField(max_length=32),
        ),
    ]
