# Generated by Django 3.2.13 on 2022-09-19 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_algorithm_event_type'),
        ('interface', '0002_auto_20220919_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benzhisubscription',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='benzhisubscription',
            name='event_type_name',
        ),
        migrations.AddField(
            model_name='benzhisubscription',
            name='algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='algorithm.algorithm', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benzhiprovider',
            name='provider_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='ProviderName'),
        ),
    ]
