# Generated by Django 3.2.13 on 2022-10-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_benzhisubscription_algorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenzhiEventToAlgorithm',
        ),
    ]
