# Generated by Django 3.2.13 on 2022-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_delete_benzhieventtoalgorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenzhiMetadata',
        ),
        migrations.DeleteModel(
            name='BenzhiProvider',
        ),
        migrations.AddField(
            model_name='benzhireporturl',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Report Enabled'),
        ),
        migrations.AddField(
            model_name='benzhireporturl',
            name='metadata',
            field=models.CharField(max_length=2048, null=True, verbose_name='Metadata (key, value) pairs in JSON format'),
        ),
        migrations.AddField(
            model_name='benzhireporturl',
            name='provider_name',
            field=models.CharField(default='美云数字', max_length=32, verbose_name='ProviderName'),
        ),
        migrations.AlterField(
            model_name='benzhireporturl',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL to Report Alert'),
        ),
    ]
