# Generated by Django 3.2.7 on 2022-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='是否开启推送')),
                ('address', models.CharField(max_length=15, verbose_name='设备地址')),
            ],
        ),
        migrations.CreateModel(
            name='PushUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.BooleanField(default=True, verbose_name='Base64编码')),
                ('url', models.CharField(max_length=1024, verbose_name='推送地址')),
            ],
        ),
    ]
