# Generated by Django 3.2.7 on 2022-07-20 13:23

import algorithm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(unique=True, verbose_name='通道编号')),
                ('cid', models.CharField(max_length=32, unique=True, verbose_name='通道识别ID')),
                ('name', models.CharField(max_length=64, verbose_name='通道名称')),
                ('site', models.CharField(max_length=64, verbose_name='通道位置')),
                ('url', models.CharField(max_length=1024, verbose_name='通道RTSP网址')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_rect', models.CharField(max_length=20, null=True, verbose_name='POI矩形区')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.algorithm', verbose_name='算法')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel', verbose_name='通道')),
            ],
            bases=(models.Model, algorithm.models.AlgorithmParametersMixin),
        ),
    ]
