# Generated by Django 3.2.13 on 2022-11-07 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(unique=True, verbose_name='通道编号')),
                ('cid', models.CharField(max_length=32, unique=True, verbose_name='通道ID')),
                ('name', models.CharField(max_length=64, verbose_name='通道名称')),
                ('site', models.CharField(max_length=64, verbose_name='通道位置')),
                ('url', models.CharField(max_length=1024, verbose_name='通道RTSP网址')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyze_interval', models.IntegerField(default=1000, verbose_name='分析问题(ms)')),
                ('alert_interval', models.IntegerField(default=30, verbose_name='报警间隔')),
                ('alert_threshold', models.FloatField(default=0.5, verbose_name='报警阈值')),
                ('alert_times', models.CharField(max_length=1792, null=True, verbose_name='报警时段')),
                ('roi_region', models.CharField(max_length=1024, null=True, verbose_name='ROI矩形区')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.algorithm', verbose_name='算法')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel', verbose_name='通道')),
            ],
            options={
                'unique_together': {('channel', 'algorithm')},
            },
        ),
    ]
