# Generated by Django 3.2.7 on 2022-07-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelalgorithm',
            name='poi_rect',
        ),
        migrations.AddField(
            model_name='channelalgorithm',
            name='roi_rect',
            field=models.CharField(max_length=20, null=True, verbose_name='ROI矩形区'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='cid',
            field=models.CharField(max_length=32, unique=True, verbose_name='通道ID'),
        ),
    ]
