# Generated by Django 3.2.7 on 2022-07-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20220723_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelalgorithm',
            old_name='roi_rect',
            new_name='roi_region',
        ),
    ]
