# Generated by Django 3.2.7 on 2022-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_rename_roi_rect_channelalgorithm_roi_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelalgorithm',
            name='alert_interval',
            field=models.IntegerField(default=30, verbose_name='报警间隔'),
        ),
        migrations.AddField(
            model_name='channelalgorithm',
            name='alert_threshold',
            field=models.IntegerField(default=0.5, verbose_name='报警阈值'),
        ),
        migrations.AddField(
            model_name='channelalgorithm',
            name='alert_times',
            field=models.CharField(max_length=1792, null=True, verbose_name='报警时段'),
        ),
        migrations.AddField(
            model_name='channelalgorithm',
            name='analyze_interval',
            field=models.IntegerField(default=1000, verbose_name='分析问题(ms)'),
        ),
    ]
