# Generated by Django 3.2.7 on 2022-07-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_delete_algorithmparameters'),
        ('channel', '0004_auto_20220725_0049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelalgorithm',
            unique_together={('channel', 'algorithm')},
        ),
    ]
