# Generated by Django 3.2.13 on 2022-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_alter_channelalgorithm_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelalgorithm',
            name='alert_threshold',
            field=models.FloatField(default=0.5, verbose_name='报警阈值'),
        ),
    ]
