# Generated by Django 3.2.13 on 2022-08-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_alter_channelalgorithm_alert_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelalgorithm',
            name='roi_region',
            field=models.CharField(max_length=1024, null=True, verbose_name='ROI矩形区'),
        ),
    ]
