# Generated by Django 3.2.13 on 2022-09-19 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_channelalgorithm_roi_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='channel',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
